apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordcount
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordcount
    spec:
      containers:
        - name: akka-cluster
          image: freakymaster/akka-cluster
          imagePullPolicy: Always
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CLUSTER_ROLES
            value: wordcount
          ports:
          - containerPort: 8080
          - containerPort: 2551
          resources:
            requests:
              cpu: 0.2
              memory: 256Mi
            limits:
              cpu: 0.3
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 40
---
kind: Service
apiVersion: v1
metadata:
  name: wordcount
spec:
  selector:
    app: wordcount
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: akka-cluster
          image: freakymaster/akka-cluster
          imagePullPolicy: Always
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_ROLES
              value: master
          ports:
            - containerPort: 2551
          resources:
            requests:
              cpu: 0.2
              memory: 256Mi
            limits:
              cpu: 0.3
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 2551
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: 2551
            initialDelaySeconds: 30
            periodSeconds: 40
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: akka-cluster
        image: freakymaster/akka-cluster
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_ROLES
          value: worker
        ports:
        - containerPort: 2551
        resources:
          requests:
            cpu: 0.2
            memory: 256Mi
          limits:
            cpu: 0.3
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 10
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 30
          periodSeconds: 40
